export {default as SignIn} from './LogIn/SignIn'
export {default as SignUp} from './LogIn/SignUp'
// export {default as Home} from './Home'
// export {default as StepOne} from './Steps/StepOne'
// export {default as SelectSchool} from './Steps/SelectSchool'
// export {default as SelectCourse} from './Steps/SelectCourse'
